name: build

env:
  VERSION: ${{ format('{0}.{1}.{2}', 0, 2, github.run_number) }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: audiostreamingplatform/hdlcpp:1.0
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build for X86
      run: scripts/build_x86.sh
    - name: Run unit tests
      run: scripts/run_tests.sh
    - name: Generate coverage
      run: scripts/coverage.sh
    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        files: .build-x86/coverage.xml
        flags: unit-tests
        name: hdlcpp
