name: build

env:
  VERSION: ${{ format('{0}.{1}.{2}', 0, 2, github.run_number) }}
  GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  develop:
    runs-on: ubuntu-latest
    container:
      image: audiostreamingplatform/hdlcpp:1.0
    steps:
    - name: Clean checkout
      run: |
        git checkout origin/develop || true
        ./build.sh -c || true
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: false
    - name: Build for X86
      run: build.sh -b
    - name: Run unit tests
      run: build.sh -t
