name: build

env:
  VERSION: ${{ format('{0}.{1}.{2}', 0, 2, github.run_number) }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: audiostreamingplatform/hdlcpp:1.0
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: false
    - name: Clean checkout
      run: build.sh -c
    - name: Build for X86
      run: build.sh -b
    - name: Run unit tests
      run: build.sh -t
